### ISSUE TITLE
Mono(non SBS) Polynomial_Barrel_Distortion option  for trinus.

### ISSUE THREAD

**Issue by damiangr** [BlueSkyDefender/Depth3D#1]
Hi.
Thank you for your great work!

It is possible to add option to Polynomial_Barrel_Distortion.fx that it will only add distortion to mono image?
Apps like trinus can duplicate half of the screen to fake SBS mode.

**Comment by BlueSkyDefender** [comment]
Ya, it can be done for a single screen. I will update that when I have time.

**Comment by BlueSkyDefender** [comment]
Don't think I have forgotten. I have just been busy with the main shader. I will add this tomorrow.

**Comment by damiangr** [comment]
Great.:) I tried myself but i know nothing about shaders (only a little c and c++).

**Comment by BlueSkyDefender** [comment]
The update should be up in the Experimental folder as Polynomial_Barrel_Distortion_v1.1.fx

I apologize that I didn't leave many notes in the core code part.

**Comment by BlueSkyDefender** [comment]
If you know c and c++ maybe you can help with a custom version of ReShade injector.

ReShade is open sourced. https://github.com/crosire/reshade 

Maybe you can mod injector to work directly with your VR headset.

**Comment by damiangr** [comment]
> The update should be up in the Experimental folder as Polynomial_Barrel_Distortion_v1.1.fx

Thank you ! :) I've just added IPD to the MONOSCOPIC code for x offset calibration.

**Comment by BlueSkyDefender** [comment]
The reason I left it out was because I thought the program must have its own IPD correction.

**Comment by damiangr** [comment]
You are right.  Trinus have IPD. 
In this case IPD  in reshade works  like  x offset  calibration (Both screens are shifted in the same direction).
I need this  because :
1.Screen is left justified when i use zoom parameter
So i have to compensate x position.
2. My phone is not perfectly aligned in The gear vr.
