### ISSUE TITLE
Failed to compile,error X5631

### ISSUE THREAD

**Issue by DjokHedgehog** [BlueSkyDefender/Depth3D#100]
Any ideas how to fix this?
![x5631](https://github.com/BlueSkyDefender/Depth3D/assets/150273623/53817f5f-17b5-44d4-bf26-8bb84a457088)

**Comment by BlueSkyDefender** [comment]
The image is not loading. But, a few things you can try. Make sure the
latest version of overwatch.fxh header file is also next to the 3D Shader


Also tell me what game you are using and what API it is.

**Comment by DjokHedgehog** [comment]
Borderlands 2, DirectX 9

**Comment by BlueSkyDefender** [comment]
I will check it out when I get home.

**Comment by DjokHedgehog** [comment]
Reupload image. Please see.

**Comment by BlueSkyDefender** [comment]
DX9 issue was fixed
