### ISSUE TITLE
[SuperDepth3D_VR+.fx] failed to compile

### ISSUE THREAD

**Issue by redthista** [BlueSkyDefender/Depth3D#108]
![image](https://github.com/BlueSkyDefender/Depth3D/assets/26851101/d5de47a1-92ef-416b-8b51-196eeee4c680)

**Comment by jack5github** [comment]
Experiencing the exact same issue, but both SuperDepth3D and SuperDepth3D_VR+ fail to compile.

**Comment by BlueSkyDefender** [comment]
This issue will be fixed next update.

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/commit/e333e5c3a82209ec3028dd0bc35b01dda5b0a598

**Comment by BlueSkyDefender** [comment]
It should be fixed. Please test the latest Update.
