### ISSUE TITLE
Licensing/Usage of Depth3D code for retooled shaders

### ISSUE THREAD

**Issue by AWBuchanan7** [BlueSkyDefender/Depth3D#11]
Would it be okay for me to use code from this repo to make "retooled" shaders forked from crosire/reshade that use your depth linearization method? I find your Depth_Tool has the adjustments I need to make shaders work with the emulator Project64, however I need to make those adjustments in DOF and MXAO as well...

**Comment by BlueSkyDefender** [comment]
Sure, Just make sure you link back to where you got the code. :) Use whatever you want. Thank you for asking.

**Comment by AWBuchanan7** [comment]
Awesome, thanks so much!

**Comment by mirh** [comment]
How about some proper license by now?
GPL sounds great if you fear "taking away and not giving back".. or is there something else concerning you?
