### ISSUE TITLE
Where on earth is the download please?...

### ISSUE THREAD

**Issue by SavedByTheLamb** [BlueSkyDefender/Depth3D#116]
Is it that:
"Depth3D VR Companion App 1.9.7 Mega Download"?...

"This Free VR App, is a basic way to view my stereoscopic shaders on your OpenXR supported HMD."
I have no idea what "OpenXR supported HMD" even means. 

Ah right, "head-mounted display (HMD)"

And do you need to install the full add-on support version of ReShade, or will the normal one work please?..

**Comment by BlueSkyDefender** [comment]
> Never mind, I found the download on the Wiki page: https://blueskydefender.github.io/Depth3D/
> 
> Still need to know if I need the full add-on support version of ReShade, or will the normal one work please?..

https://discord.com/channels/305472403977404416/1236960569219743834

If it's a online game you want to use the add-on version.  This version has Network Detection disabled.

In that case if you are playing a single player game then the normal version is ok to use.
