### ISSUE TITLE
UI Mask?

### ISSUE THREAD

**Issue by DieKatzchen** [BlueSkyDefender/Depth3D#12]
Is it possible to provide one or more masks in png format to mask UI elements? I tried using UIMask, but it excludes the masked area from being processed, rather than editing the depth map, which is what I need.

**Comment by BlueSkyDefender** [comment]
If you are talking about HUD Mode it only for UI elements that show up in the Depth Buffer.

It does edit the Depth Buffer close the cam. Not many games need this since most of the time the HUD is not drawn in the Depth Buffer. I only know of a few games where this happens.

Also, I am not sure what you need. Since I am not sure what the problem.

**Comment by DieKatzchen** [comment]
Not sure how to describe it... in Warcraft III  if you look at the depth map, it is solid white around where the UI elements should be, except that the actual UI overhangs this area slightly, making it look broken and uncomfortable to look at in 3D. I have a black and white mask of where the UI elements actually are, if I could sort of overlay that onto the depth mask before the stereo views are calculated, then the UI would look correct.

**Comment by BlueSkyDefender** [comment]
Give me time to look into the issue with this game.

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/commit/26776f5fdaf9d8fa727d90f64e8e72d8dd6acfd1

Test it out here. Both Shaders Updated.

**Comment by DieKatzchen** [comment]
It mostly works, but there's some slight doubling in the right eye, right here:
![Have a look](https://i.imgur.com/7cQaL75.png)

**Comment by BlueSkyDefender** [comment]
Send me your mask.

**Comment by BlueSkyDefender** [comment]
Ok Updated my shader. But I could not find this problem you have. The picture you sent too low rez for my eyes 🗡
