### ISSUE TITLE
How to stretch image?

### ISSUE THREAD

**Issue by FlamesoFF** [BlueSkyDefender/Depth3D#13]
It's too narrow and there is no option to make it wider per eye
![image](https://user-images.githubusercontent.com/5371279/51076208-ad9a0080-1695-11e9-8510-dc154294f86c.png)

**Comment by BlueSkyDefender** [comment]
Are you using a HMD?

If so use Polynomial Barrel Distortion Shader.

**Comment by BlueSkyDefender** [comment]
This this shader help you?

**Comment by FlamesoFF** [comment]
@BlueSkyDefender  It does the thing, but depth of the "SuperDepth3D" shader become broken

**Comment by BlueSkyDefender** [comment]
What are you trying to do exactly? Because that shader can adjust it in many different ways. Also, keep in mind shader order important.

**Comment by FlamesoFF** [comment]
@BlueSkyDefender I fixed this problem with different shader:
![image](https://user-images.githubusercontent.com/5371279/51179068-d05e2c00-18c4-11e9-9420-d48b5469eade.png)

**Comment by BlueSkyDefender** [comment]
Cool, I am glad you got it working. I think I need to leave a note somewhere on shader order. My fault.
