### ISSUE TITLE
Wrong mouse cursor positioning (virtual desktop)

### ISSUE THREAD

**Issue by HoshiYamazaki** [BlueSkyDefender/Depth3D#15]
As title says, it is caused either by virtual desktop or because there is no mouse cursor each virtual SBS screens just one global taken from Windows.

**Comment by HoshiYamazaki** [comment]
This is probably caused by using borderless windowed mode, will check it tomorrow :)

**Comment by BlueSkyDefender** [comment]
Make sure the Cross Cursor above 3D shader. Also, you change the windows cursor to something smaller.
