### ISSUE TITLE
Frame Alternation (BSI) bitwise operations not supported on target

### ISSUE THREAD

**Issue by deama** [BlueSkyDefender/Depth3D#16]
So when I try to run the Frame Alternation(BSI) shader on world of warcraft, Reshade gives an error that it can't load the shader because of some bitwise operations not supported on target, here's the full error:
BSI.fx(66,13-21): error X3535: Bitwise operations not supported on target ps_3_0

**Comment by deama** [comment]
Also, is it possible to make it work for content that plays at lower fps? Like at 30fps? Or 24?

**Comment by BlueSkyDefender** [comment]
There has to be a change to quad buffering if you want to work with lower frames. Also about the Bitwise I don't work on the shaders that I listed as Do Not Use. At this point, it's stored code.
