### ISSUE TITLE
Smart_Sharp.fx can't be compiled

### ISSUE THREAD

**Issue by Bapho** [BlueSkyDefender/Depth3D#17]
**Smart_Sharp.fx** does not compile in ReShade 3.4.0 for example...

Line 533: float3 can't be implicitly cast to float4
`Out = lerp(Sharpen, BB, DB);`

**Comment by BlueSkyDefender** [comment]
what Game?

**Comment by Bapho** [comment]
in Warcraft III
a manual cast/conversion like `Out = float4(lerp(Sharpen, BB, DB), 1.0);` seems to work in my case
