### ISSUE TITLE
[Feature Request] Halo 2 Support?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [BlueSkyDefender/Depth3D#18]
It works fo the most part, however the HUD/Weapons and Arms are separate from the scene's depth buffer. There is also a distortion effect on the crosshairs when looking around corners.

**Comment by BlueSkyDefender** [comment]
I will look into it.

**Comment by BlueSkyDefender** [comment]
Don't think this issue can be fixed unless we are allowed to select different depth buffers and merge them. Mabe the Halo 2 Modder can fix this issue in the game.

I will talk to a reshade injector Dev to see if this is an option that can be added.

Don't hold your breath. 

Distortion effect on the crosshairs / Hud items can't be helped.

**Comment by BlueSkyDefender** [comment]
MCC works a bit better with issue.
