### ISSUE TITLE
World of Warships

### ISSUE THREAD

**Issue by ExtremeDM** [BlueSkyDefender/Depth3D#19]
Hello im total new here and in this theme of reshading a program /game etc hehe.

I was wondering if someone could help me with the right settings for 3D for this game... " World of Warships " i already installed reshade, its up an running , im using oculus rift S , and Virtual Desktop app in oculus also . 

Problem i have is that when i activate Superdeep3D.fx and it runs but, i use in Virtual Desktop HALF SBS option and image looks good,but i need some help 
![World of Warships](https://user-images.githubusercontent.com/54413403/63536467-e40fe780-c4d0-11e9-89e9-33bfbfe6e1cf.jpg)
to adjust the distance between my eyes, is like not perfectly adjusted.

And the mouse movement inside the game is tottally out of range , need to do magic in order to use it .

Sorry for my bad english and i hope someone would be able to help me out . 

THANKS !!
![V Desktop](https://user-images.githubusercontent.com/54413403/63536123-28e74e80-c4d0-11e9-9240-709a628a5850.jpg)

**Comment by BlueSkyDefender** [comment]
Try this shader.

https://github.com/BlueSkyDefender/Depth3D/blob/master/Shaders/Alternative%20Shaders/Experimental/SuperDepth3D_2.0.4_VR.fx

**Comment by ExtremeDM** [comment]
Thank you for answering !

Sorry for my ignorance , after i click on the link , i cant find a window to download the shader :( 
How i download it , sorry .... :(

**Comment by BlueSkyDefender** [comment]
Download the entire package then look for the shader in the folder.

**Comment by ExtremeDM** [comment]
Got it !!, Thanks ill try it now !

**Comment by ExtremeDM** [comment]
OK the image is better, though the mouse is still out of right position , blurry as well , hmm also there is a big vignette , lag incremented also a bit

**Comment by BlueSkyDefender** [comment]
Use the shaders cursor. The vignette can be disabled. As for latency, you
need to disable effects.

Don't expect the in-game cursor to be in the proper position since the game
does not draw it where the shader can intercept it.

**Comment by ExtremeDM** [comment]
got it ! , shader cursor solve that !, dunno how to deactivate vignette, and effects you mean inside the game graphic settings ?

**Comment by BlueSkyDefender** [comment]
in shader effects to help with a clear image in VR slow down the shader a
bit. This shader also has a performance mode.
You can disable effects in the shader itself.

Set vignette to zero

**Comment by ExtremeDM** [comment]
how do i slow down the shader ? and cant find vignette :(, let me look further

**Comment by ExtremeDM** [comment]
Found vignette, Cant find Shader effects 
got 

Eye Focus Adjustment
Divergence & Convergence
Oclussion Masking
Depth map 
Weapon Map Adjustment ( THis i find interesting to clear my image , cant find the right one yet ) 
Image Adjustment
Image Effects
Cursor Adjustment

**Comment by ExtremeDM** [comment]
By the way i would like to donate something to you , for your help and for this great Work you have done with this shaders , sent me paypal name etc so i can send something. 

On the other hand , is there a way to insert shaders into windows 10 app GAMES ? 
Im in terested in killer instinct specifically . 

Problem is when i point the installer to that directory , it finds an error, as windows games dont have exe.'s like a normal installed game. So i point the only possible exe inside that folder.
![Killer 1](https://user-images.githubusercontent.com/54413403/63640035-aa69e880-c658-11e9-814a-e479e5b53ec1.jpg)

**Comment by BlueSkyDefender** [comment]
For Windows 10 app store games. You may have to wait. Because Microsoft said that mod support may be added for some games.

https://www.pcgamesn.com/windows-store-mod-support

If you enjoyed this shader and like to donate paypal.me/BlueSkyDefender

**Comment by ExtremeDM** [comment]
Thanks a lot !!!

Paypal Not working  ... with that name , or what im doing wrong ?






[cid:84c05026-1d28-499c-9de3-b673ec3cb692]

Leonardo Ladron de Guevara Diaz
Director
6241565946 · leocabo1@hotmail.com<mailto:leocabo1@hotmail.com>

Dronez Universe
Cabo San Lucas · Carretera Transpeninsular k.m. 6.5

 [YouTube] <http://www.youtube.com/channel/UCeeRZuk1zWmzGLsDKmsVxgw>  [Whatsapp]


________________________________
De: BlueSkyDefender <notifications@github.com>
Enviado: sábado, 24 de agosto de 2019 02:37 p. m.
Para: BlueSkyDefender/Depth3D <Depth3D@noreply.github.com>
CC: ExtremeDM <leocabo1@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [BlueSkyDefender/Depth3D] World of Warships (#19)


For Windows 10 app store games. You may have to wait. Because Microsoft said that mod support may be added for some games.

https://www.pcgamesn.com/windows-store-mod-support

If you enjoyed this shader and like to donate paypal.me/BlueSkyDefender

**Comment by BlueSkyDefender** [comment]
It should look like this when you click it.
[image: image.png]

**Comment by ExtremeDM** [comment]
Sorry bro cant click what you send ....

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by BlueSkyDefender** [comment]
It's a picture. Is what you should see when you click the link:
https://www.paypal.me/BlueSkyDefender

**Comment by ExtremeDM** [comment]
Done ! sent you 5 bucks bro , thanks for the help ! , I read about what you sent of microsoft
, i have thhe latest update and  ModifiableWindowsApps folder is already there but empty
dunno what to do hehe..

One last question , How can i decrease Sreen Door efect  ? Using the shaders specially the 3D one
which setting/s HELP on this matter specifically ?

Thanks a lot again

Best Regards Leo


[cid:c5fd4c5f-ea99-430e-87ef-d29a63a63aba]

Leonardo Ladron de Guevara Diaz
Director
6241565946 · leocabo1@hotmail.com<mailto:leocabo1@hotmail.com>

Dronez Universe
Cabo San Lucas · Carretera Transpeninsular k.m. 6.5

 [YouTube] <http://www.youtube.com/channel/UCeeRZuk1zWmzGLsDKmsVxgw>  [Whatsapp]


________________________________
De: BlueSkyDefender <notifications@github.com>
Enviado: sábado, 24 de agosto de 2019 04:07 p. m.
Para: BlueSkyDefender/Depth3D <Depth3D@noreply.github.com>
CC: ExtremeDM <leocabo1@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [BlueSkyDefender/Depth3D] World of Warships (#19)

It's a picture. Is what you should see when you click the link:
https://www.paypal.me/BlueSkyDefender

**Comment by BlueSkyDefender** [comment]
The screen door effect is coming from your HMD. I can't control that
physical aspect of that screen with a shader.

**Comment by ExtremeDM** [comment]
Ok thanks bro! Good day !

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by ExtremeDM** [comment]
Hello Blue,

Sorry i have this problem with some games, no clue why is happening .

Mainly project cars 2

When i lunch the game, it always open steam VR , and if steam VR and oculus is running , Reshade
DONT load.....

If i stop Steam VR and oculus service ( Force stop Before starting the game ) Reshade always load and everything is fine.

Do you know how can i solve this  ?


Best Regards

Leo


[cid:06546252-6006-4993-ad1b-02a801f5bb5a]

Leonardo Ladron de Guevara Diaz
Director
6241565946 · leocabo1@hotmail.com<mailto:leocabo1@hotmail.com>

Dronez Universe
Cabo San Lucas · Carretera Transpeninsular k.m. 6.5

 [YouTube] <http://www.youtube.com/channel/UCeeRZuk1zWmzGLsDKmsVxgw>  [Whatsapp]


________________________________
De: BlueSkyDefender <notifications@github.com>
Enviado: sábado, 24 de agosto de 2019 06:46 p. m.
Para: BlueSkyDefender/Depth3D <Depth3D@noreply.github.com>
CC: ExtremeDM <leocabo1@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [BlueSkyDefender/Depth3D] World of Warships (#19)

The screen door effect is coming from your HMD. I can't control that
physical aspect of that screen with a shader.
