### ISSUE TITLE
Can't create username on reshade.me forum

### ISSUE THREAD

**Issue by markbradley1982** [BlueSkyDefender/Depth3D#2]
I know this isn't the best place to write it, but I couldn't find any other way to make contact.
 
The https://reshade.me forum has no way to create new accounts now. If you click create a new account, it just redirects you make to reshade.me instead of a form to create a new username. Do you know anyone that can fix this?

**Comment by BlueSkyDefender** [comment]
Try a different browser like Windows edge. Other than that I don't know.
Since I don't manage that forum.

**Comment by BlueSkyDefender** [comment]
Player unknown's Battlegrounds that an online game right. Some time in
online games the depth map is deactivated. This is done to keep people from
using reshade as a way to cheat. This my understanding as to why.

This shader is open so that if there is a way to create a shader in HLSL or
GLSL you can use my code to directly with the game if you like.

Feel free to do so.

Sometimes it looks like reshade doesn't play well with Unreal Engine 4
engine. Have you tried TriDef? I apologize for the inconvenience.

**Comment by markbradley1982** [comment]
No need to apologise. I haven't confirmed yet if the depth map is disabled or not. I haven't tried tridef though I have heard it performs worse than your shader, and if the depth map is disabled then its z buffer 3D option probably won't work. They offer a geometric 3D mode as well though you take a big performance hit.
 
I currently use vorpx most games since I have a headset. It works great on unreal engine 3 games like rocket league, but doesn't work on unreal engine 4 games. In the worst case I may have to settle for just playing battlegrounds on a giant 2d screen in my headset instead of 3D. Thanks for your email!

**Comment by BlueSkyDefender** [comment]
Yes for now. I will be updating it for a monoscopic image when I have time.

**Comment by BlueSkyDefender** [comment]
I am working on an easier Depth Map system with 1.9.6 Update This should help a lot with setting depth map precision. It just takes some time to check 100+ games.

But, even in the state that 1.9.6 you should use it to set your depth map for your game. Since this update should be out in a week.

**Comment by markbradley1982** [comment]
Ah I see.
 
What is the difference between the depth maps? Do the higher numbered depth maps give stronger depth? What about the depth setting then? Is it possible to have a depth setting higher than 30?

Let me know what your Paypal is. I feel I owe you a donation for all of these questions.

**Comment by BlueSkyDefender** [comment]
As 1-30 Depth maps were just different precision equations. Since reshade gives out raw z-buffer from the game. 

So because I was still was learning how to code I didn't quite know how to do this well at first. I did self-teach myself to code this shader better over time. 

Update 1.9.6 only has 10 Depth Maps since I worked on fixing redundancy. I will Try to see if I can narrow Down even more for next update. Since I want to make it as easy as possible for people to use. This for of 3D is very sensitive to Depth Buffer precision. 

So moving over to 1.9.6 should be easier for everyone.

As for the donation, I have a PayPal Me link.

 If you enjoyed this shader and like to donate PayPal.me/BlueSkyDefender

**Comment by markbradley1982** [comment]
I just sent you $20. Is it possible to have the depth setting go beyond 30? On May Payne 3, I can only go to 30 it seems.On May 10, 2017 at 4:42 AM BlueSkyDefender <notifications@github.com> wrote:As 1-30 Depth maps were just different precision equations. Since reshade gives out raw z-buffer from the game.So because I was still was learning how to code I didn't quite know how to do this well at first. I did self-teach myself to code this shader better over time.Update 1.9.6 only has 10 Depth Maps since I worked on fixing redundancy. I will Try to see if I can narrow Down even more for next update. Since I want to make it as easy as possible for people to use. This for of 3D is very sensitive to Depth Buffer precision.So moving over to 1.9.6 should be easier for everyone.As for the donation, I have a PayPal Me link.If you enjoyed this shader and like to donate PayPal.me/BlueSkyDefender—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by BlueSkyDefender** [comment]
On the new 1.9.6 and the old 1.9.5, you can go beyond the limits. To do that, you need to double click Divergence Slider or on the old shader, it's called Depth Slider. When you do this you can enter any amount.

Keep in mind distortions may get out of hand when doing this. Part of the reason I have a soft limit was to limit the Distortions.

Overriding limits may have some unintended outcomes on the image. Just keep in mind you don't want too much depth as it can also cause eye strain/headaches.

Also, thank you for the donation.

**Comment by markbradley1982** [comment]
What resources did you use to learn shader programming? Currently I am learning C# along with Unity. I really appreciate the good work you did with this.There's another wrapper and set of shaders called 3Dmigoto with converts 3d vision into side by side and over/under. But it only works with Direct X 11.Is there anyway for you to create some sort of shader that converts Nvidia 3D vision to over/under that works with Direct X 9, 10, and 11 games? There's so many games that support 3d vision, especially with a very dedicated community who make custom profiles. Plus 3D vision offers not only Z buffer but also true geometric 3D.Think you could pull this off? I am willing to put up $200 if you can do this. A lot of people would benefit. If you don't think that's enough, let me know. My dream is to be able to use 3D vision in my Vive, and converting it to over/under and SBS would be the ticket to do that. On May 10, 2017 at 6:12 AM BlueSkyDefender <notifications@github.com> wrote:On the new 1.9.6 and the old 1.9.5, you can go beyond the limits. To do that, you need to double click Divergence Slider or on the old shader, it's called Depth Slider. When you do this you can enter any amount.Keep in mind distortions may get out of hand when doing this. Part of the reason I have a soft limit was to limit the Distortions.Overriding limits may have some unintended outcomes on the image. Just keep in mind you don't want too much depth as it can also cause eye strain/headaches.Also, thank you for the donation.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by markbradley1982** [comment]
Is there any documentation or wiki where I can see what each feature does? For example I was messing with the near and far settings and that seemed to affect the depth in Max Payne 3 as well. On May 10, 2017 at 6:12 AM BlueSkyDefender <notifications@github.com> wrote:On the new 1.9.6 and the old 1.9.5, you can go beyond the limits. To do that, you need to double click Divergence Slider or on the old shader, it's called Depth Slider. When you do this you can enter any amount.Keep in mind distortions may get out of hand when doing this. Part of the reason I have a soft limit was to limit the Distortions.Overriding limits may have some unintended outcomes on the image. Just keep in mind you don't want too much depth as it can also cause eye strain/headaches.Also, thank you for the donation.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by BlueSkyDefender** [comment]
The only reason I don't work and avoided 3D vision was that I wanted to stay hardware agnostic. That's why I didn't teach myself how to do the 3D vision fixes.

As for what each feature does. I did try to self-label many things in my shader. So if you look in the Depth Map part you should see notes I left behind for this. This is in 1.9.6 also if you follow the uniform you can see what section they control in the shader. Also, this language is Reshade FX. 

https://github.com/crosire/reshade-shaders/blob/master/REFERENCE.md

But, if you are looking to make this work with DX12/Vulcan you may want to program this into the main ReShade injector. 

ReShade is open sourced. https://github.com/crosire/reshade Maybe you can add a buffer so that we can use  Frame Sequential. Or mod the Depth Buffer for Framed Packed mode.

**Comment by markbradley1982** [comment]
I see. Okay I understand. For games with the depth buffer cleared, are there any alternative methods of creating Z buffer like quasi 3D without a full geometric 3D reconstruction?On May 10, 2017 at 7:00 PM BlueSkyDefender <notifications@github.com> wrote:The only reason I don't work and avoided 3D vision was that I wanted to stay hardware agnostic. That's why I didn't teach myself how to do the 3D vision fixes.As for what each feature does. I did try to self-label many things in my shader. So if you look in the Depth Map part you should see notes I left behind for this. This is in 1.9.6 also if you follow the uniform you can see what section they control in the shader. Also, this language is Reshade FX.https://github.com/crosire/reshade-shaders/blob/master/REFERENCE.mdBut, if you are looking to make this work with DX12/Vulcan you may want to program this into the main ReShade injector.ReShade is open sourced. https://github.com/crosire/reshade Maybe you can add a buffer so that we can use Frame Sequential. Or mod the Depth Buffer for Framed Packed mode.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by BlueSkyDefender** [comment]
That part can be changed to here a forum post talking about it. 

https://reshade.me/forum/general-discussion/3059-depth-buffer-question-for-crosire

**Comment by markbradley1982** [comment]
Interesting! Thanks for the link!On May 10, 2017 at 7:53 PM BlueSkyDefender <notifications@github.com> wrote:That part can be changed to here a forum post talking about it.https://reshade.me/forum/general-discussion/3059-depth-buffer-question-for-crosire—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by markbradley1982** [comment]
If the depth buffer can't be accessed for a particular game what does Reshade and/or your shader do? Does it give an error?On May 10, 2017 at 7:53 PM BlueSkyDefender <notifications@github.com> wrote:That part can be changed to here a forum post talking about it.https://reshade.me/forum/general-discussion/3059-depth-buffer-question-for-crosire—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by BlueSkyDefender** [comment]
My shader will not produce a 3D image. It will just split the image. 2D to
3D conversion not good enough so I didn't add a 2D to 3D converter.  I did
try but the image quality was really bad.

**Comment by BlueSkyDefender** [comment]
Ya, I think it can be done. But, work on that should be apart and develop on its own.

**Comment by markbradley1982** [comment]
Is it possible for you to share what you have so I can see about possibly expanding on this project? This is interesting.On May 10, 2017 at 11:26 PM BlueSkyDefender <notifications@github.com> wrote:Ya, I think it can be done. But, work on that should be apart and develop on its own.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by BlueSkyDefender** [comment]
Ya, I can share it. But, it looks like a dead end. I will need to upgrade it to work with reshade 3.0. This will be after I finish 1.9.6. Just give me time.

**Comment by markbradley1982** [comment]
Sure no problem. We'll see how it goes I guess. Maybe you are right. Does the occasional artifact kill your immersion?On May 11, 2017 at 12:41 AM BlueSkyDefender <notifications@github.com> wrote:Ya, I can share it. But, it looks like a dead end. I will need to upgrade it to work with reshade 3.0. This will be after I finish 1.9.6. Just give me time.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by BlueSkyDefender** [comment]
You learn to ignore it after some time. It gets better at higher resolutions.

**Comment by markbradley1982** [comment]
If the depthmap is pure white, does that always mean that the Z buffer can't be accessed? Because in Chivalry the depthmap is always a solid white, but the game clearly looks 3D when depth3D is enabled. Additionally the Reshade games compatibility list doesnt mention not being able to access the depth buffer. On May 11, 2017 at 12:56 AM BlueSkyDefender <notifications@github.com> wrote:You learn to ignore it after some time. It gets better at higher resolutions.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by BlueSkyDefender** [comment]
The depth map may pop in and out if it's an online game. But, I can't be sure since I can't test the game itself. Since I don't have it.

**Comment by markbradley1982** [comment]
Interesting. Is there some sort of a cache if a depth map is captured? Because with Chivalry I consistently see good 3D depth but whenever I switch over I only see a white screen on the depth map. On May 14, 2017 at 6:26 PM BlueSkyDefender <notifications@github.com> wrote:The depth map may pop in and out if it's an online game. But, I can't be sure since I can't test the game itself. Since I don't have it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mark BradleyCircle Six Limited

**Comment by BlueSkyDefender** [comment]
No there is not. The depth output is the same one shader sees.
