### ISSUE TITLE
Polynomial barrel distortion black and white

### ISSUE THREAD

**Issue by tk7018** [BlueSkyDefender/Depth3D#20]
If i use the polynomial barrel distortion shader i always get a blac and white image regardless of the saturation setting.
It seems to be related to the distortion shader becuse if i put the 3D depth. As last one i get full color (even if the image is unusable).

**Comment by BlueSkyDefender** [comment]
I will look into this when I have time.

**Comment by AutumnalAntlers** [comment]
Having the same issue here, I've only tried Oblivion but with several versions of Reshade, the standard and experimental versions of SuperDepth3D, all load orders and settings; the standard Depth3D included with reshade works just fine but any other version desaturates when loaded prior to Barrel Distortion. Can't find any other mention of the issue online. My mouse cursor is also all kinds of screwed in-game, but that's reshade's fault :p

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/commit/5a75b61f5393e85ac81b195156ec439847471208

I fixed the issue.

**Comment by tk7018** [comment]
It works now thanks
