### ISSUE TITLE
Doing native mouse support

### ISSUE THREAD

**Issue by HoshiYamazaki** [BlueSkyDefender/Depth3D#22]
Hey, I reply to my previous issue:

https://github.com/BlueSkyDefender/Depth3D/issues/15

Why we can't do native mouse support in Reshade? Can we just display instead of dot the same cursor that is in game in both virtual screens?

**Comment by BlueSkyDefender** [comment]
Not an issue to do with SuperDepth3D.

But there is a workaround for this.

https://reshade.me/forum/shader-troubleshooting/5357-depth3d-and-total-war-warhammer-2-mouse-cursor

**Comment by BlueSkyDefender** [comment]
Also in the "game help.txt," there is a mini-guide.

**Comment by HoshiYamazaki** [comment]
> Also in the "game help.txt," there is a mini-guide.

Can't you just make option "Default cursor"? So if you select it the cursor have the same as the in game. Why we must override it via custom image?

**Comment by BlueSkyDefender** [comment]
Like I said before this is not a SuperDepth3D issue.  Can't do this with shader level configurations.
