### ISSUE TITLE
SuperDepth3D VR experimental version does not compile

### ISSUE THREAD

**Issue by HoshiYamazaki** [BlueSkyDefender/Depth3D#23]
![image](https://user-images.githubusercontent.com/21007545/71450346-a5c95400-2760-11ea-9d83-fa37a99bf4e8.png)

I wanted to test SuperDepth3D VR version, and it doesn't compile.

**Comment by BlueSkyDefender** [comment]
For now, don't use the VR version. It's still a work in progress.

**Comment by frostworx** [comment]
Hi there!
I'm the linux guy whose reddit thread you found :)
I noticed that the VR version doesn't compile (complains about a float3 which should be a float4) and wonder if this issue still is valid. 
Thank you for your cool shader! :)

**Comment by BlueSkyDefender** [comment]
What line is it giving this error on?

**Comment by frostworx** [comment]
thanks for your interest!
this is the error in the log:
22:37:58:276 [00188] | ERROR | Failed to compile "Z:\\media\\ssdeam2\\SteamLibrary\\steamapps\\common\\Legend of Grimrock\\SuperDepth3D_VR.fx":
Z:\media\ssdeam2\SteamLibrary\steamapps\common\Legend of Grimrock\SuperDepth3D_VR.fx(1491,19-35): error X3017: cannot convert from 'float3' to 'float4'

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/blob/b4efd384489d97def24073402d6525423d7cb714/Shaders/SuperDepth3D_VR.fx#L1491-L1494

So I did this change. Please tell me if it works.

I also added a new profile for that game Legend of Grimrock and updated the shader with a new option that used in this profile.

**Comment by frostworx** [comment]
wow, you're fast! I can confirm that this fixes the issue under linux. thank you very much!

**Comment by frostworx** [comment]
:)
