### ISSUE TITLE
Private Info Shared. ...

### ISSUE THREAD

**Issue by ExtremeDM** [BlueSkyDefender/Depth3D#25]
Hello bro , 

 Got a problem of privacy if you mind , helping me please, when i look for my email on google 
which is  : "EDITED OUT"@hotmail.com    it appears in diferrent sites , which is ok , but specially on this one it appear also my personal celphone, would you be so kind of erasing that comment please ? ill aprecciate it !!! thanks bro ! and thanks for your work ! again !

**Comment by BlueSkyDefender** [comment]
I can remove the email address as soon as I find it.

**Comment by BlueSkyDefender** [comment]
There we go I think I got all instances of your email.

**Comment by BlueSkyDefender** [comment]
Seems to be fixed

**Comment by ExtremeDM** [comment]
Thanks a lot bro !!

Sorry the bother!!

Best regards !

Enviado desde mi Samsung Mobile de Telcel
Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________
