### ISSUE TITLE
Companion App - Desktop duplication Api

### ISSUE THREAD

**Issue by Dillotu** [BlueSkyDefender/Depth3D#27]
Hi 

I'm trying to run the Companion App in a Laptop Dell with a dedicated 1050ti GPU. 
Unfortunately I'm not able to run in the 1050 but only in the integrated 630 intel GPU.

I have a Headset Lenovo Explorer and if the Companion app runs without the headset it shows the desktop (set to run with the ingrated GPU) if instead I plug the headset it gives me the notification above Desktop duplication Api even if I set to run with the integrated app.

Is there any workaround to fix it? 

Looks like a limitation of the Microsoft Hybrid system https://support.microsoft.com/en-us/help/3019314/error-generated-when-desktop-duplication-api-capable-application-is-ru

Thanks

**Comment by BlueSkyDefender** [comment]
Did you try to disable your IGPU in the Device Manager? Leaving only your DGPU accessible. Ya, With Windows API Limitations It is not easy to deal with.

**Comment by Dillotu** [comment]
Hi BlueskyDefender

Done also this test but it does not work. 

Disabling the iGPU the Companion App remains with a black background.

**Comment by Azorico** [comment]
I am facing this exact problem. @Dillotu did you manage to find a workaround?
