### ISSUE TITLE
Companion aspect ratio

### ISSUE THREAD

**Issue by tk7018** [BlueSkyDefender/Depth3D#28]
Aspect ratio of the companion app seems to be 16:9 regardless of the original desktop/game ratio. Would it be possible to make it manually adjustable?

**Comment by BlueSkyDefender** [comment]
I can make the change. I just have not got around to it.

**Comment by BlueSkyDefender** [comment]
This now apart of the Depth3D Companion App 1.9

It creates the screen on app start up and adjust based on the screen's Aspect Ratio.
