### ISSUE TITLE
Setting for the position/offset of the rendered output.

### ISSUE THREAD

**Issue by RobertZenz** [BlueSkyDefender/Depth3D#29]
An offset/position option, which allows to adjust the Y position of the final image, would be a nice to have.

My cheap mobilephone/VR set favors the top part of the screen, which means that I have hard time seeing the lower part of the rendered image, however, I'm seeing a large black area above it, obviously. So having an option that allows me to adjust the Y position of the image on the screen would be nice, as then I could move it upwards to see everything.

**Comment by BlueSkyDefender** [comment]
For what shader you're talking about?

**Comment by RobertZenz** [comment]
Sorry, SuperDepth3D/SuperDepth3D_VR. To be exact, when used in the side-by-side mode.

**Comment by BlueSkyDefender** [comment]
Because, there is a shader that meant to fix this issue. For now. Do you want this option added to the VR shader?

https://youtu.be/tFNNoztpSN8

**Comment by RobertZenz** [comment]
Yes, like that...but minus the distortion would be nice, as the "normal" SuperDepth3D shader works for me very well, with the exception of the position.

**Comment by BlueSkyDefender** [comment]
![image](https://user-images.githubusercontent.com/16185319/90343496-747dec80-dfac-11ea-9b8e-36a5637917ba.png)
Set this shader to this. To remove distortion. I will need to add this option when I have time. So for now use this shader.

**Comment by RobertZenz** [comment]
Thank you very much, that looks good.
