### ISSUE TITLE
How I'm supposed to use this?

### ISSUE THREAD

**Issue by IamKayrox** [BlueSkyDefender/Depth3D#31]
I installed Reshade and this shader. I started the game and enabled the shader. But now I only have a split view on my screen. Tried using the Companion App but I oly get my screen floating on front of me with the game in split view. What I have to do to run this in VR through my headset?

**Comment by BlueSkyDefender** [comment]
https://www.youtube.com/watch?v=ICyZ0SrOdZo
https://cdn.discordapp.com/attachments/686542138418135172/686785881587187880/KeyLayout.png

Look at the following information to guide you.
