### ISSUE TITLE
SuperDepth3D crashes Assassins Creed Valhalla in Quests/Inventory/etc.

### ISSUE THREAD

**Issue by dborosev** [BlueSkyDefender/Depth3D#33]
Works great while playing the game, but very very often will crash when going into the menus to check inventory, look at maps, look at quests, etc.   
Works longer if not in "performance mode", but still locks the game up very often like this too.  
Any ideas on how to solve this?

**Comment by BlueSkyDefender** [comment]
Seems to be solved with latest reshade.
