### ISSUE TITLE
Cyberpunk 2077 Incompatible with Depth3D

### ISSUE THREAD

**Issue by PeterTucker** [BlueSkyDefender/Depth3D#34]
Unfortunately, it looks like Depth3D does not work with Cyberpunk 2077. Half the screen is covered in black artifacts. Any fixes?

**Comment by BlueSkyDefender** [comment]
Use ReShade 4.0.7 Mod Some users reported it working. I have not checked my self since I don't own the game. But, they said it work when selecting some option in the API tab. Must be working because they don't respond much after learning this. So they must be playing.  :D

**Comment by einsz** [comment]
Where to get "ReShade 4.0.7 Mod" version?

**Comment by PeterTucker** [comment]
Hi BlueSkyDefender, I also would like to know where to get ReShade 4.0.7. I looked online and could not find any details regarding downloading that version. Any help would be appreciated. Thaks!

**Comment by PeterTucker** [comment]
> Where to get this "ReShade 4.0.7 Mod" version?

@BlueSkyDefender  I would also like to know where you can get version 4.0.7. I checked the official reshade repository and version 4.0.7 is nowhere to be found. Much appreciated!

**Comment by BlueSkyDefender** [comment]
So I was also told by some users that the normal version of 4.7.0 works. To download older versions of ReShade Just change the download link to the version you need.
Ex. https://reshade.me/downloads/ReShade_Setup_4.8.2.exe > https://reshade.me/downloads/ReShade_Setup_4.7.0.exe

**Comment by PeterTucker** [comment]
Hmmm, I tested with 4.7.0, unfortunately it doesn't work. Was it 4.7.0 or
4.0.7?

**Comment by BlueSkyDefender** [comment]
More information here too https://reshade.me/forum/shader-presentation/2128-3d-depth-map-based-stereoscopic-shader?start=1500#40243

**Comment by BlueSkyDefender** [comment]
4.9.1 works now

**Comment by frostworx** [comment]
Contratulations you got it working!
Likely an amdgpu problem, as you require mesa-git to properly play Cyberpunk, but might be interesting to know that it does not work under linux using SteamPlay/Proton yet (tried with previously required experimental builds and also proton-5.13-5).
ReShade 4.9.1 itself works _(f.e. Flipbook shader works)_, but as soon as you enable Depth3D the whole game freezes.
Tested with a RX 6900 XT.

**Comment by DaddyWesker** [comment]
"Half the screen is covered in black artifacts"

I have the same problem using newest reshade version. Any depth-related shaders in CP2077 just filling some part of the image with artifacts. Though everything works fine in the cutscenes. 

![20230126213341_1](https://user-images.githubusercontent.com/10774222/214920500-81bb4676-8044-41c2-a860-69d371ce02ce.jpg)


Maybe someone knows how to fix that or some better place to ask this question?

**Comment by BlueSkyDefender** [comment]
I will look into this. Also may I ask what is your GPU?

**Comment by DaddyWesker** [comment]
@BlueSkyDefender 
MSI Nvidia RTX 4090

I've beat (i hope) problem with artifacts using checkbox "copy depth buffer to prevent afrifacts", so no afrtifacts currently. But i need to re-check this since I've already thought that eveyrthing is fine but it wasn't

SuperDepth3D I haven't tested after this fix. I'll check and get back with result.
