### ISSUE TITLE
3DToElse (Interlaced to SBS or NV3D-Ready) not working 

### ISSUE THREAD

**Issue by oocyberkevinoo** [BlueSkyDefender/Depth3D#35]
Hi, I'm trying to use the Nvidia VIsion 3D rendering on my VR Headset, so your 3DToElse shader seems to be exactly what I need, but the result is... well, like it don't get the correct information to SBS...

![image](https://user-images.githubusercontent.com/22883203/103591280-fafd8100-4eef-11eb-8c3b-008a34bf7de6.png)

(tested on a lot of Reshade version)

EDIT : Also, has Nvidia Vision Ready monitors are simple Frame Sequential render, there's not a way to adapt the frame sequential input for Nvidia specific render ? (or maybe it is already but as my monitor enable 3D it cause issue ?)

**Comment by BlueSkyDefender** [comment]
It will not work because 3DVision applies after ReShade Not before.  Use 3DMigoto.

**Comment by oocyberkevinoo** [comment]
I see, but 3DMigoto only work for Direct X 11 games, am I right ?

Actually, I tried to see how it react in Virtual Desktop trying to get the frames from Nvidia Vision by getting one frame on two, and SOMETIMES it correctly got the left frame on the left, and right frame on the right.
I wonder if we can't just apply a frame buffer to keep the previous frame and show it on one side, then another as it seems like ReShade can access those rendered frames correctly in the end.
