### ISSUE TITLE
CoD: MW3 SuperDepth3D.fx compile error on ReShade 3.1.2

### ISSUE THREAD

**Issue by FalkenStein42** [BlueSkyDefender/Depth3D#36]
Im attaching a screenshot with the error description. I know this is not the latest version of ReShade by far, but its the only version that doenst make mw3 crash instantly -even with no shaders loaded-.
I recall trying out an older version of the file? where the same error was present but it worked anyway. Is there an archive for the Depth3D version files?

Note: Tried to run everything again with dgvoodoo2 jic but have gotten the same results so far. 

![error](https://user-images.githubusercontent.com/47744227/104955092-e4642900-59c9-11eb-8020-9c27901b1473.png)

**Comment by BlueSkyDefender** [comment]
Let me look into this.

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/commit/82d79b34e11bdc02b3cb51cc0aa78ef60c825b63

It's Fixed now.
