### ISSUE TITLE
Request: 3d alternates to side by side

### ISSUE THREAD

**Issue by i00** [BlueSkyDefender/Depth3D#37]
I have a TV where every 1st line is the left and every 2nd line is the right eye...
Can you please add a setting for this so that:
- A. I don't loose 1/2 the horiz resolution when I change the tv to side by side
- B. I don't have to touch the tv remote to enable 3d :P

Great work BTW;
Thanks :)

**Comment by BlueSkyDefender** [comment]
Give me your screen  tech information and specs.

**Comment by i00** [comment]
I have a few different LG tv models and they all work like this:
![image](https://user-images.githubusercontent.com/1435262/105473696-1c7cac00-5ce9-11eb-9d9d-c38b5742cffe.png)
.. bottom right is what the image looks like zoomed in ... so as you can see each lens filters every other line

Model series are:
-LB6500-TH
-LM6200-TA

Thanks

**Comment by BlueSkyDefender** [comment]
There is an option in the shader to swap Eyes Try that. 

https://github.com/BlueSkyDefender/Depth3D/wiki/Shader-Adjustments#stereoscopic-options

**Comment by i00** [comment]
No ... I mean instead of side by side, have another option so every 2nd line is one eye and every other line is the other

**Comment by i00** [comment]
Ahh cool ... i see now thanks
