### ISSUE TITLE
How exactly do i do this?

### ISSUE THREAD

**Issue by SweetBabyJezuz** [BlueSkyDefender/Depth3D#39]
https://prnt.sc/y5qxa7
I have no idea, thank you.

**Comment by SweetBabyJezuz** [comment]
I have i5 7th gen and GeForce gtx 1050

**Comment by Picoseconds** [comment]
Hello @BlueSkyDefender  what is the workarounds that you know for hybrid systems? I have this problem and dont want to use my slow i7 gpu

**Comment by BlueSkyDefender** [comment]
Other users just disabled there IGPU. It seems to work for them.
