### ISSUE TITLE
Dual settings for barrel distortion suggestion

### ISSUE THREAD

**Issue by tk7018** [BlueSkyDefender/Depth3D#4]
Would it be possibile to add the possibily  tà to switch between 2 differenti sets of barrel distortion settings using a key?

In particolar i would like two different zoom levels to be abile to read  the information at the corner of the screen while using the full Fov of the lenses the test of the time.
I tried to achieve this by using 2 istances of the barrel distortion FX (of course not at the same time) but on of the two always edn up in a black screen.
Another request would be to be abile to rotate the video matrix to simulate head roll using a joystick axis or another kind of input. 
Thanks in advance.

**Comment by BlueSkyDefender** [comment]
Would it be possibile to add the possibily tà to switch between 2 differenti sets of barrel distortion settings using a key?

Ya, It should be possible. I will add to the ToDo list. 

I Don't have access to games Matrix to do this for your 2nd Request.

**Comment by tk7018** [comment]
thank you, as for the second request maybe i misexplained myself. 
if i understand correctly the barrel distortion generates a (2 actually) texture that is then  processed to generate the distorted view. If this is the technique  used, is it possible to rotate the texture before applying the distortion to simulate head roll (a slider adjustable with 2 keys  to change value in  a range of 180 degrees would be enough for testing purposes)?

**Comment by BlueSkyDefender** [comment]
Ok, I had time to update PBD. I want to know what game had this problem. So I can test my work around.

**Comment by tk7018** [comment]
I tried aliens colonoal marines and AVP. I saw the update im goi g to try the new release soon thank you for the update.

**Comment by BlueSkyDefender** [comment]
OK Thank you for telling me the game. 
Now the update is live.

In the shader line 28 you need to change it from 0 to 1 if you use two of the same shader.

https://github.com/BlueSkyDefender/Depth3D/blob/5daa62ffe49ac1885c903320bba625d1e26f7d58/Shaders/Alternative%20Shaders/Experimental/Polynomial_Barrel_Distortion_v1.2.fx#L25-L28

1. So take one Polynomial_Barrel_Distortion_v1.2.fx

2. Rename too Polynomial_Barrel_Distortion_v1.2_M.fx  

3. Copy this shader and paste it.

4. Rename the copy too  Polynomial_Barrel_Distortion_v1.2_S.fx,

5. Open Polynomial_Barrel_Distortion_v1.2_S.fx and go to line 28.

6. Change One to Zero. From "#define TOGGLE 1" To "#define TOGGLE 0"

**Comment by tk7018** [comment]
It works flawlessly with colonial marines (i i was in a rush so i could not test other games, but i thhink it will work too)!!!!

**Comment by tk7018** [comment]
I also saw the rotation option, that more or less what i was trying to expalin you that i needed (sorry for the confusion). 
Would it be possible to set the rotation value with an external control (trackir or direct x joystick value) to simulate head roll for vr games (or even crate a separate shader that does only that before the 3d or the barrel distortion)?

**Comment by BlueSkyDefender** [comment]
You need to find a programmer that can give me access to rotation values in reshade so I can add head tracking. As you can see, I am able to the work on the shader side. But, not edit reshade self. At least not yet. I don't have the free time to learn how to edit some thing that complicated. But, since it is open to modification.
