### ISSUE TITLE
SuperDepth3D_VR+ "Performance Mode" Error with "Fable Anniversary" (DirectX 9; under Linux using Proton)

### ISSUE THREAD

**Issue by frostworx** [BlueSkyDefender/Depth3D#40]
Hi,
When trying to enable the "Performance Mode" in SuperDepth3D_VR+ with the DirectX9 game "Fable Anniversary" under Linux using Proton _(in case that matters)_, the shaders fails with:
```
19:03:30:277 [00500] | ERROR | Failed initializing "Z:\media\B4-1\SteamLibrary\steamapps\common\Fable Anniversary\Binaries\Win32\SuperDepth3D_VR+.fx":
Z:\media\B4-1\SteamLibrary\steamapps\common\Fable Anniversary\Binaries\Win32\SuperDepth3D_VR+.fx(179, 3): preprocessor warning: Will NOT work on DirectX 9.0c and OpenGL at current resolution.
Z:\media\B4-1\SteamLibrary\steamapps\common\Fable Anniversary\Binaries\Win32\SuperDepth3D_VR+.fx(982,15-39): warning X4008: floating point division by zero
Z:\media\B4-1\SteamLibrary\steamapps\common\Fable Anniversary\Binaries\Win32\SuperDepth3D_VR+.fx(829,16-53): warning X4008: floating point division by zero
Z:\media\B4-1\SteamLibrary\steamapps\common\Fable Anniversary\Binaries\Win32\SuperDepth3D_VR+.fx(829,16-53): error X4579: NaN and infinity literals not allowed by shader model
```

The Shader works fine with the game with "Performance Mode" disabled.

"Performance Mode" works though with the game "Bendy and the Ink Machine" which is a DirectX9 game as well
_(and also logs the "preprocessor warning: Will NOT work on DirectX 9.0c and OpenGL at current resolution" warning)_

I can easily live with this non-fatal glitch,
but if you are interested and need anything else for testing/debugging please let me know.

**Comment by BlueSkyDefender** [comment]
Let me look into this Thank you for bring this up to my attention.

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/commit/998656228ab3096e3cf7bb4e292e6abfcf21d8ac

Should be fixed.

**Comment by frostworx** [comment]
Wow, that was fast! Thank you very much for your great work again!
 I can confirm that it works now also on Linux.
