### ISSUE TITLE
The Depth3D Companion app triggers the virus scanner

### ISSUE THREAD

**Issue by atkulp** [BlueSkyDefender/Depth3D#41]
Windows 10 identifies this file as a trojan called "Trojan:Win32/Wacatac.DF!ml".  Can you upload a new version?

**Comment by BlueSkyDefender** [comment]
Sounds like a false positive. But, even then I will run a scan of my system.

**Comment by Knifa** [comment]
![image](https://user-images.githubusercontent.com/622619/108773884-e2f0c800-7556-11eb-8b7f-c1daad84ca9e.png)

From VirusTotal.

But yes, mainly it triggers the Windows 10 built-in scanner right away.

**Comment by BlueSkyDefender** [comment]
Thank you I am using this in my submission to Microsoft.

**Comment by BlueSkyDefender** [comment]
1.9 is out so I am closing this issue.
