### ISSUE TITLE
Final fantasy 13

### ISSUE THREAD

**Issue by Nhussaini79** [BlueSkyDefender/Depth3D#54]
I installed reshade and checked the depth 3d as per your instructions i watched in a video. I then selected super depth 3d from the list. I booted up the game and hit the home button. When i try to enable super depth 3d it is red and no options at the bottom to change the depth or separation. When i hover over super depth 3d it says failed to compile. Then it shows my path of the game with error x3531 can’t unroll loops marked with loop attribute. It says to enable performance mode. So i enable performance mode and then i can checkmark super depth 3d and play the game with 3d. However i would like to increase depth and separation so i uncheckmark performance mode and i see the options and slider i can use to change for just a second and it goes away and the super depth 3d tab turns red again with that error above. The game looks pretty good but i really want to increase the depth and separation. Any help would be appreciated.

**Comment by BlueSkyDefender** [comment]
I will look into it. Just give me time to download the game.

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/commit/75f2149c315f784f5b3c650bc130b8ee9a95b8c0

Should be fixed

**Comment by Nhussaini79** [comment]
You’re welcome man. Thanks for the fix and quick response
