### ISSUE TITLE
Blurry effect around characters

### ISSUE THREAD

**Issue by Nhussaini79** [BlueSkyDefender/Depth3D#56]
Hey man I've had some great success in using super depth 3d vr.  One of my favorites is Tales of zestiria.  The 3d is pushed back really good.  I have also tested prince of persia the forgotten sands and ori and I have been really impressed.  One of the games you helped me fix was final fantasy 13 and I love the 3d affect in it.  However when I push it back and change the Divergence Slider to 150 because I really enjoy the 3d with that setting a blur kinda shows up around the characters.  The game runs perfect and I enjoy the 3d affect but that blur just gets annoying during the cutscenes.  Is there any setting I can do to try and clear that up or is that just part of the depth3d and what it does?

**Comment by BlueSkyDefender** [comment]
When games do not have a profile a user needs to make one. Problem is I can't make a profile for every game. So milage may very. TBH max Divergence is about 125 anything larger the shader has a hard time filling that empty information in. Halos are covered up missing information. Keep in mind follow the warning information of the shader don't Max out anything. Profile creation takes time and the shader evolves. If you are using overwatch.fxh the check out the profile fore Re7 to get a idea of how 3D should look like. Use the latest shader. You should only need to set Divergence and your screen 3D type ± your favorite view mode.

**Comment by Nhussaini79** [comment]
I don't know how to create a profile.  I just followed your video on setting up super depth 3d vr +.  You didn't show anything on that video on creating a profile.  I have no clue how to use overwatch.  I do have it in the directory where super depth 3d vr is but no clue on how to use it.  Tales of zestiria works great in 150 divergence and looks fantastic with no blur.

**Comment by Nhussaini79** [comment]
I'm going to close this issue.  I have played around with some of the settings and have improved and pretty much removed the blur affect.
