### ISSUE TITLE
Many DirectX games crashes on AMD notebook graphics card.

### ISSUE THREAD

**Issue by StuDentBRz** [BlueSkyDefender/Depth3D#6]
Many DirectX games crashes when i try to use depth3d on my notebook  that uses AMD HD 8850m (r9m200x) and Intel core i5 3320m (HD graphics 4000) ,maybe It has something to do with hybrid graphics cards. The only thing that worked was project64 OpenGL.

**Comment by BlueSkyDefender** [comment]
Is this just my shader? Please test another shader for me, please.

**Comment by StuDentBRz** [comment]
i will test it again, and soon i will tell you, but if i am not wrong it crashes even before i can activate any shader.

**Comment by StuDentBRz** [comment]
Ok i've just tested it and the issue is not only with your shader but with reshader itself, anyway i tested with the witcher 3 and after i've changed the "dxgi.ini" to "d3d11.ini" it worked ok.

**Comment by StuDentBRz** [comment]
i will close the issue, thank you.
