### ISSUE TITLE
HDR Broken in Reconstruction mode list os and games 

### ISSUE THREAD

**Issue by x8009** [BlueSkyDefender/Depth3D#72]
Games, for example, NFS HEAT, Assassin's Creed Origin, Shadow of the TombRaider, and Star Wars Jedi Fallen Order.

Using 3.5.0 until 3.2.5 doesn't work properly.
3.2.0 and below it works fine.

To test
Enable Windows HDR
Using Superdepth3D 3.2.5 and above with Reshade X.X doesn't matter as long Super depth can compile
Enable Game HDR
Enable Reconstruction Mode 1
The game looks washed with no brightness, overbright and fewer colors.

Disable Reconstruction mode, it works fine.

**Comment by BlueSkyDefender** [comment]
This issue is fixed now use HDR compatibility preprocessor at the bottom of the shader.  Set it to one.
