### ISSUE TITLE
How-to tips to access the DepthBuffer in games not on your list

### ISSUE THREAD

**Issue by apollon01** [BlueSkyDefender/Depth3D#8]
Hi BlueSkyDefender and big thanks for the Depth3D!

I am "playing" with the Depth3D for some time now with diverse success. My goal is to (if possible) get it running for a series of flight simulators: Prepar3D, Flight Sim World, FSX, X Plane 11, DCS, Il2 Cliffs of Dover and Rise of Flight.

None of these is on the list of games supported.

So far, I was successful only with Flight Sim World but only when I disabled the anti-aliasing. There are some artefacts in the image but all in all it is pretty good :-)

I have gone through the various settings you suggest for various games on your list to get a flavour of what might work for the sims I list, but...

...would you have some general tips how the DepthBuffer could be usually accessed by your Depth3D? I would give it a try and report back in case of success.

Thank you!

Regards,
Milan

**Comment by BlueSkyDefender** [comment]
This depends on ReShades Depth Compatibility list. https://reshade.me/compatibility

Not all game hand over there depth buffer so easily.

**Comment by apollon01** [comment]
OK, thank you.
