### ISSUE TITLE
Diablo 4

### ISSUE THREAD

**Issue by cyrilpreiss** [BlueSkyDefender/Depth3D#82]
Hi, did anybody find a way to make it work with diablo 4 ?
shr00ns on  the reshade forum said he managed to make it work using reshade version with full addon support but didn't say more.
i have installed this version but it doesn't change anything.

**Comment by BlueSkyDefender** [comment]
You will need to use the ReShade version with add on support. I will be looking in to this game today. No profile was made yet since I was really busy this month. 

Will get to it when I can.

**Comment by cyrilpreiss** [comment]
Hi, i had tried the add on support versin with no luck. Yesterday i tried to set performance mode to normal and it's working now. They are issues, especialy with the hud, but it's in 3D at least !
Thanks for working on the profile for us ! Please let us know when it's done !

**Comment by BlueSkyDefender** [comment]
I am working on a workaround.

**Comment by BlueSkyDefender** [comment]
Try out the new profile I uploaded it.

**Comment by cyrilpreiss** [comment]
Thanks so much for you so quick action ! 
Unfortunately i didn't understand yet how to use the auto profile.
I have tried to get the settings from Overwatch.fxh and set them manually. But they are some settings i didn't find.
Could you point me to an help on how to use Overwatch.fxh ?
Event if it's not perfect yet as i haven't set all the settings it's already great. Playing diablo 4 on the pimax crystal is so great !!!! thanks to you !

**Comment by BlueSkyDefender** [comment]
You need to just download the reshade again and install it again.

Just download the Shader again.

Then reset the settings of the Shader.

**Comment by cyrilpreiss** [comment]
Thanks it's working so great now !!!

Just one thing, why don't you reply about the request i and others have made about making background black ? 
This is so annoying to have this moon killing the immersion :-( please do something about it !

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/issues/82

This Profile has be fixed. Now it's in maintenance mode pending future updates.
