### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by Dabonsi** [BlueSkyDefender/Depth3D#89]
Hi I Have this Problem:
![grafik](https://github.com/BlueSkyDefender/Depth3D/assets/133366478/b6371067-0391-445a-8ce0-ee6e0a96e9d3)
Can anybody help with that?

**Comment by BlueSkyDefender** [comment]
Found the issue will be patching this problem tonight.

**Comment by Dabonsi** [comment]
Can you tell here when the Code is cleared?

**Comment by BlueSkyDefender** [comment]
Ran into a internet Issue. Will get it uploaded when my home internet is
back up and running. IRL hold up.

**Comment by BlueSkyDefender** [comment]
https://github.com/BlueSkyDefender/Depth3D/commit/42a1f7505d94b6b8ee7d1b61920a126a47f885d8

Should be fixed now.
