### ISSUE TITLE
Foreground hud / UI is displayed in only one eye

### ISSUE THREAD

**Issue by vipero07** [BlueSkyDefender/Depth3D#9]
This shader mostly works with gw2 except the UI and all the names are displayed on a separate 2d flat map, I'm fairly certain this isn't unique to gw2 but I'm not sure how to make it so the ui is just duplicated to both images. Still playable, if you disable all ui elements though, great work.

**Comment by BlueSkyDefender** [comment]
If the hud shows up in the depth buffer you should be able to adjust with the Weapon Depth Map HUD option.

**Comment by vipero07** [comment]
When I use display depth on the depth tool the hud doesn't change color at all, I've tried all the weapon depth map options (including the hud one) and it doesn't effect the ui. Attached are some screenshots of what I mean. My best guess is its not in the depth buffer at all but rather rendered in a separate 2d buffer.

SBS
![gw051](https://user-images.githubusercontent.com/4421342/35485027-2ddd9af4-0427-11e8-8089-cf3b7e1f0687.jpg)

Depth Tool
![screenshot using the depth tool](https://user-images.githubusercontent.com/4421342/35484972-6d7a946a-0426-11e8-9bed-f10fd596ef61.jpg)

**Comment by BlueSkyDefender** [comment]
The only kind of 3d that will work with this is anaglyph, Interlaced, & checkerboard 3D. Looks like you may be using a modded version of Reshade. If this is the case ask the modder of your ReShade version to Adjust 2D elements to TnB and Side By Side with a Toggle.

**Comment by vipero07** [comment]
Yes, unfortunately reshade dislikes gw2 because of network traffic (though they may have changed that block with reshade 3 iirc). Unfortunately I'm a bit limited to what kind of 3d to display to either SBS or TnB, but your comment made me realize top and bottom may work better since at least then most 2d elements would appear where they should be (albeit in only one eye). I will see if I can contact that dev to make adjustments to the 2d elements though. Additionally I feel a bit dumb, as I forgot their mod intentionally handles the shaders after the hud is drawn so the hud is unaffected by things like blur shaders. Feel free to close this ticket, thanks for pointing me in the right the direction.

**Comment by vipero07** [comment]
Quick update, using reshade 3 works fine and has no issue, also TnB works-ish when using the modded reshade, mostly because one eye sees the overlay in the right area.

**Comment by BlueSkyDefender** [comment]
Can you link me to the modded version please?

**Comment by BlueSkyDefender** [comment]
Thank you.
