### ISSUE TITLE
Getting black corruption on the screen

### ISSUE THREAD

**Issue by FlogramMatt** [BlueSkyDefender/Depth3D#97]
Having this reshade issue:
https://reshade.me/forum/shader-troubleshooting/9124-black-corruption-on-screen#46217

Seems to only happen with reshades that use depth in cyberpunk. Wasn't happening on AMD 7900xt using reshade through luke ross mod. Then switched over to direct reshade for Depth3d on RTX 4080(I returned 7900xt as I wanted ray tracing) and now it's happening. Usually happens, not always hard to pinpoint anything beyond there, have tried turning various settings on and off which don't seem to affect it, though maybe new ray tracing was linked or something.

Any thoughts on what I could do next to debug? Thanks

**Comment by FlogramMatt** [comment]
Same thing with "Immortals of Aveum"

**Comment by BlueSkyDefender** [comment]
Enable Both Copy methods in the the Add-on tab under the Generic Depth Add-on.

![image](https://github.com/BlueSkyDefender/Depth3D/assets/16185319/df9e6741-e56d-4c8d-a659-6221c07822f9)

**Comment by FlogramMatt** [comment]
Awesome, that does it, thanks Blue!
